services:
  - type: web
    name: resumegpt
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true
